#port
server.port=8081
#config datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacy_db_hwss09_mcs
spring.datasource.username=postgres
spring.datasource.password=123456
#config JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#info
app.branch-name=Nha Thuoc So 1
app.hotline=19001234
management.endpoints.web.exposure.include=refresh,health,info
pharmacy.vat-rate=0.1

resilience4j.circuitbreaker.metrics.enabled=true
resilience4j.circuitbreaker.instances.doctorService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.doctorService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.doctorService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.doctorService.permitted-number-of-calls-in-half-open-state=3
