#port
server.port=8081
#config datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacy_db_hwss09_mcs
spring.datasource.username=postgres
spring.datasource.password=123456
#config JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#info
app.branch-name=Nha Thuoc So 1
app.hotline=19001234
pharmacy.vat-rate=0.1
